import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { HttpClientModule } from '@angular/common/http';

import { ChartjsModule } from '@coreui/angular-chartjs';

// Importing CoreUI modules
import {
  AccordionModule,
  AlertModule,
  BadgeModule,
  BreadcrumbModule,
  ButtonGroupModule,
  ButtonModule,
  CardModule,
  CarouselModule,
  CollapseModule,
  DropdownModule,
  FormModule,
  GridModule,
  ListGroupModule,
  ModalModule,
  NavbarModule,
  NavModule,
  PaginationModule,
  PlaceholderModule,
  PopoverModule,
  ProgressModule,
  SharedModule,
  SpinnerModule,
  TableModule,
  TabsModule,
  ToastModule,
  TooltipModule,
  UtilitiesModule,
} from '@coreui/angular';

import { IconModule } from '@coreui/icons-angular';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,
    HttpClientModule,
    ButtonModule,
    ButtonGroupModule,
    GridModule,
    IconModule,
    CardModule,
    UtilitiesModule,
    DropdownModule,
    SharedModule,
    FormModule,
    NavbarModule,
    CollapseModule,
    NavModule,
    AccordionModule,
    BadgeModule,
    BreadcrumbModule,
    ListGroupModule,
    PlaceholderModule,
    ProgressModule,
    SpinnerModule,
    TabsModule,
    TooltipModule,
    CarouselModule,
    PaginationModule,
    PopoverModule,
    TableModule,
    ModalModule,
    ToastModule,
    ChartjsModule,
    AlertModule,
  ],
  exports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,
    HttpClientModule,
    ButtonModule,
    ButtonGroupModule,
    GridModule,
    IconModule,
    CardModule,
    UtilitiesModule,
    DropdownModule,
    SharedModule,
    FormModule,
    NavbarModule,
    CollapseModule,
    NavModule,
    AccordionModule,
    BadgeModule,
    BreadcrumbModule,
    ListGroupModule,
    PlaceholderModule,
    ProgressModule,
    SpinnerModule,
    TabsModule,
    TooltipModule,
    CarouselModule,
    PaginationModule,
    PopoverModule,
    TableModule,
    ModalModule,
    ToastModule,
    ChartjsModule,
    AlertModule,
  ],
  declarations: [
    // Declare your components here, e.g.,
    // AppComponent,
    // RealGraphComponent
  ],
})
export class NplModule {}

// Your root AppModule should import `NplModule` and should have `BrowserModule` imported.
