import { Component } from '@angular/core';
import {
  RowComponent,
  ColComponent,
  TextColorDirective,
  CardComponent,
  CardHeaderComponent,
  CardBodyComponent,
  CardTitleDirective,
  CardTextDirective,
  ButtonDirective,
  CardSubtitleDirective,
  CardLinkDirective,
  ListGroupDirective,
  ListGroupItemDirective,
  CardFooterComponent,
  NavComponent,
  NavItemComponent,
  NavLinkDirective,
  BorderDirective,
  CardGroupComponent,
  GutterDirective,
  CardImgDirective,
} from '@coreui/angular';

@Component({
  selector: 'app-white-rabbit',
  standalone: true,
  imports: [RowComponent,
    ColComponent,
    TextColorDirective,
    CardComponent,
    CardHeaderComponent,
    CardBodyComponent,
    CardTitleDirective,
    CardTextDirective,
    ButtonDirective,
    CardSubtitleDirective,
    CardLinkDirective,
    ListGroupDirective,
    ListGroupItemDirective,
    CardFooterComponent,
    NavComponent,
    NavItemComponent,
    NavLinkDirective,
    BorderDirective,
    CardGroupComponent,
    GutterDirective,
    CardImgDirective,
  ],
  templateUrl: './white-rabbit.component.html',
  styleUrl: './white-rabbit.component.scss'
})
export class WhiteRabbitComponent {
}
